CREATE TABLE IF NOT EXISTS Users (
	id SERIAL PRIMARY KEY,
	nickname VARCHAR NOT NULL UNIQUE,
	email VARCHAR NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	password VARCHAR NOT NULL
);




