// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/account/v1/account.proto

package accountv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegError int32

const (
	RegError_ERROR_UNDEFINED               RegError = 0
	RegError_ERROR_EMAIL_ALREADY_EXISTS    RegError = 1
	RegError_ERROR_NICKNAME_ALREADY_EXISTS RegError = 2
	RegError_ERROR_DB_CONN                 RegError = 3
	RegError_ERROR_DISK_FULL               RegError = 4
	RegError_ERROR_GRPC_CONN_TIMEOUT       RegError = 5
	RegError_ERROR_TLS_HANDSHAKE_FAULT     RegError = 6
	RegError_ERROR_BLACKLIST_EMAIL         RegError = 7
)

// Enum value maps for RegError.
var (
	RegError_name = map[int32]string{
		0: "ERROR_UNDEFINED",
		1: "ERROR_EMAIL_ALREADY_EXISTS",
		2: "ERROR_NICKNAME_ALREADY_EXISTS",
		3: "ERROR_DB_CONN",
		4: "ERROR_DISK_FULL",
		5: "ERROR_GRPC_CONN_TIMEOUT",
		6: "ERROR_TLS_HANDSHAKE_FAULT",
		7: "ERROR_BLACKLIST_EMAIL",
	}
	RegError_value = map[string]int32{
		"ERROR_UNDEFINED":               0,
		"ERROR_EMAIL_ALREADY_EXISTS":    1,
		"ERROR_NICKNAME_ALREADY_EXISTS": 2,
		"ERROR_DB_CONN":                 3,
		"ERROR_DISK_FULL":               4,
		"ERROR_GRPC_CONN_TIMEOUT":       5,
		"ERROR_TLS_HANDSHAKE_FAULT":     6,
		"ERROR_BLACKLIST_EMAIL":         7,
	}
)

func (x RegError) Enum() *RegError {
	p := new(RegError)
	*p = x
	return p
}

func (x RegError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegError) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_account_v1_account_proto_enumTypes[0].Descriptor()
}

func (RegError) Type() protoreflect.EnumType {
	return &file_proto_account_v1_account_proto_enumTypes[0]
}

func (x RegError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegError.Descriptor instead.
func (RegError) EnumDescriptor() ([]byte, []int) {
	return file_proto_account_v1_account_proto_rawDescGZIP(), []int{0}
}

type RegUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegUserRequest) Reset() {
	*x = RegUserRequest{}
	mi := &file_proto_account_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegUserRequest) ProtoMessage() {}

func (x *RegUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegUserRequest.ProtoReflect.Descriptor instead.
func (*RegUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *RegUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         RegError               `protobuf:"varint,3,opt,name=error,proto3,enum=account.v1.RegError" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegUserResponse) Reset() {
	*x = RegUserResponse{}
	mi := &file_proto_account_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegUserResponse) ProtoMessage() {}

func (x *RegUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegUserResponse.ProtoReflect.Descriptor instead.
func (*RegUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *RegUserResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegUserResponse) GetError() RegError {
	if x != nil {
		return x.Error
	}
	return RegError_ERROR_UNDEFINED
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_proto_account_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_v1_account_proto_rawDescGZIP(), []int{2}
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_proto_account_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAllResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GetAllResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_account_v1_account_proto protoreflect.FileDescriptor

const file_proto_account_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/account/v1/account.proto\x12\n" +
	"account.v1\"f\n" +
	"\x0eRegUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"g\n" +
	"\x0fRegUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12*\n" +
	"\x05error\x18\x03 \x01(\x0e2\x14.account.v1.RegErrorR\x05error\"\x0f\n" +
	"\rGetAllRequest\"X\n" +
	"\x0eGetAllResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*\xe1\x01\n" +
	"\bRegError\x12\x13\n" +
	"\x0fERROR_UNDEFINED\x10\x00\x12\x1e\n" +
	"\x1aERROR_EMAIL_ALREADY_EXISTS\x10\x01\x12!\n" +
	"\x1dERROR_NICKNAME_ALREADY_EXISTS\x10\x02\x12\x11\n" +
	"\rERROR_DB_CONN\x10\x03\x12\x13\n" +
	"\x0fERROR_DISK_FULL\x10\x04\x12\x1b\n" +
	"\x17ERROR_GRPC_CONN_TIMEOUT\x10\x05\x12\x1d\n" +
	"\x19ERROR_TLS_HANDSHAKE_FAULT\x10\x06\x12\x19\n" +
	"\x15ERROR_BLACKLIST_EMAIL\x10\a2\x9b\x01\n" +
	"\x0eAccountService\x12C\n" +
	"\bRegister\x12\x1a.account.v1.RegUserRequest\x1a\x1b.account.v1.RegUserResponse\x12D\n" +
	"\vGetAllUsers\x12\x19.account.v1.GetAllRequest\x1a\x1a.account.v1.GetAllResponseB2Z0github.com/TSX97/INK3/proto/account/v1;accountv1b\x06proto3"

var (
	file_proto_account_v1_account_proto_rawDescOnce sync.Once
	file_proto_account_v1_account_proto_rawDescData []byte
)

func file_proto_account_v1_account_proto_rawDescGZIP() []byte {
	file_proto_account_v1_account_proto_rawDescOnce.Do(func() {
		file_proto_account_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_account_v1_account_proto_rawDesc), len(file_proto_account_v1_account_proto_rawDesc)))
	})
	return file_proto_account_v1_account_proto_rawDescData
}

var file_proto_account_v1_account_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_account_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_account_v1_account_proto_goTypes = []any{
	(RegError)(0),           // 0: account.v1.RegError
	(*RegUserRequest)(nil),  // 1: account.v1.RegUserRequest
	(*RegUserResponse)(nil), // 2: account.v1.RegUserResponse
	(*GetAllRequest)(nil),   // 3: account.v1.GetAllRequest
	(*GetAllResponse)(nil),  // 4: account.v1.GetAllResponse
}
var file_proto_account_v1_account_proto_depIdxs = []int32{
	0, // 0: account.v1.RegUserResponse.error:type_name -> account.v1.RegError
	1, // 1: account.v1.AccountService.Register:input_type -> account.v1.RegUserRequest
	3, // 2: account.v1.AccountService.GetAllUsers:input_type -> account.v1.GetAllRequest
	2, // 3: account.v1.AccountService.Register:output_type -> account.v1.RegUserResponse
	4, // 4: account.v1.AccountService.GetAllUsers:output_type -> account.v1.GetAllResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_account_v1_account_proto_init() }
func file_proto_account_v1_account_proto_init() {
	if File_proto_account_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_account_v1_account_proto_rawDesc), len(file_proto_account_v1_account_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_account_v1_account_proto_goTypes,
		DependencyIndexes: file_proto_account_v1_account_proto_depIdxs,
		EnumInfos:         file_proto_account_v1_account_proto_enumTypes,
		MessageInfos:      file_proto_account_v1_account_proto_msgTypes,
	}.Build()
	File_proto_account_v1_account_proto = out.File
	file_proto_account_v1_account_proto_goTypes = nil
	file_proto_account_v1_account_proto_depIdxs = nil
}
